### ISSUE TITLE
Fix to Python example for version 3

### ISSUE THREAD

**Issue by bryanminorphd** [seomoz/Social-Authority-SDK#7]
Attached is an updated version of the Python example how to use the Social Authority for version 3.  There is a *.py and an example Jupyter notebook. Please let me know if you have any questions. 

Thanks, 
Bryan Minor 
bryan@envision.ai

[SocialAuthority_Twitter_Moz_Python3.zip](https://github.com/seomoz/Social-Authority-SDK/files/1282994/SocialAuthority_Twitter_Moz_Python3.zip)

**Comment by semifor** [comment]
Thank you for your update @bryanminorphd. I'm not a python dev, myself, but with the guidance of someone who is, I modified the code you submitted a bit so it runs with both python2 and python3. You'll find the result at https://github.com/seomoz/Social-Authority-SDK/blob/master/code-examples/python.py.
